name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          protocol: ftps
          port: 21
          server: ${{ secrets.SAKURA_HOST }}
          username: ${{ secrets.SAKURA_USER }}
          password: ${{ secrets.SAKURA_PASSWORD }}
          local-dir: /home/runner/work/laravel_deployToSakura/laravel_deployToSakura/
          server-dir: laravel_deployToSakura/
          log-level: verbose
          security: loose

